# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDonet@2
  displayName: 'Use .Net Core SDK 3.1.100'
  inputs:
    packageType: sdk
    version: 3.1.100

- task: npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false
- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs: 
    command: 'restore'
    projects: '**/*.csproj'

- task: DonetCoreCLI@2
  displayName: 'Build the project - Release'
  Inputs: 
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'

 
